### ISSUE TITLE
Submit happens twice

### ISSUE THREAD

**Issue by zemogle** [LCOGT/serol#3]
All requests are submitted twice, a few seconds apart.

**Comment by zemogle** [comment]
I think I've fixed this. Deployed

**Comment by zemogle** [comment]
Definitely did not fix this.

**Comment by zemogle** [comment]
Still no idea why this happens but I've put in logging which seems to have stopped it....

**Comment by zemogle** [comment]
Finally tracked this down. Looks like state change doesn't quite work so function is called twice in some instances:

```
29/01/2018 11:26:05Traceback (most recent call last):
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
29/01/2018 11:26:05    response = get_response(request)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
29/01/2018 11:26:05    response = self.process_exception_by_middleware(e, request)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
29/01/2018 11:26:05    response = wrapped_callback(request, *callback_args, **callback_kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
29/01/2018 11:26:05    return view_func(*args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
29/01/2018 11:26:05    return self.dispatch(request, *args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
29/01/2018 11:26:05    response = self.handle_exception(exc)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
29/01/2018 11:26:05    self.raise_uncaught_exception(exc)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
29/01/2018 11:26:05    response = handler(request, *args, **kwargs)
29/01/2018 11:26:05  File "./status/views.py", line 59, in post
29/01/2018 11:26:05    resp = ser.save(user=request.user)
29/01/2018 11:26:05  File "./status/views.py", line 37, in save
29/01/2018 11:26:05    resp_prog = save_progress(challenge=params['challenge'], user=kwargs['user'], request_id=resp_msg, target=params['object_name'])
29/01/2018 11:26:05  File "./status/views.py", line 92, in save_progress
29/01/2018 11:26:05    progress.submit()
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django_fsm/__init__.py", line 515, in _change_state
29/01/2018 11:26:05    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django_fsm/__init__.py", line 299, in change_state
29/01/2018 11:26:05    object=instance, method=method)
29/01/2018 11:26:05TransitionNotAllowed: Can't switch from state 'Submitted' using method 'submit'
ERROR:django.request:Internal Server Error: /api/schedule/
29/01/2018 11:26:05Traceback (most recent call last):
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
29/01/2018 11:26:05    response = get_response(request)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
29/01/2018 11:26:05    response = self.process_exception_by_middleware(e, request)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
29/01/2018 11:26:05    response = wrapped_callback(request, *callback_args, **callback_kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
29/01/2018 11:26:05    return view_func(*args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
29/01/2018 11:26:05    return self.dispatch(request, *args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
29/01/2018 11:26:05    response = self.handle_exception(exc)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
29/01/2018 11:26:05    self.raise_uncaught_exception(exc)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
29/01/2018 11:26:05    response = handler(request, *args, **kwargs)
29/01/2018 11:26:05  File "./status/views.py", line 59, in post
29/01/2018 11:26:05    resp = ser.save(user=request.user)
29/01/2018 11:26:05  File "./status/views.py", line 37, in save
29/01/2018 11:26:05    resp_prog = save_progress(challenge=params['challenge'], user=kwargs['user'], request_id=resp_msg, target=params['object_name'])
29/01/2018 11:26:05  File "./status/views.py", line 92, in save_progress
29/01/2018 11:26:05    progress.submit()
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django_fsm/__init__.py", line 515, in _change_state
29/01/2018 11:26:05    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
29/01/2018 11:26:05  File "/usr/lib/python2.7/site-packages/django_fsm/__init__.py", line 299, in change_state
29/01/2018 11:26:05    object=instance, method=method)
29/01/2018 11:26:05TransitionNotAllowed: Can't switch from state 'Submitted' using method 'submit'
29/01/2018 11:26:05[pid: 34|app: 0|req: 19/77] 10.42.201.252 () {62 vars in 1206 bytes} [Mon Jan 29 11:26:04 2018] POST /api/schedule/ => generated 10446 bytes in 499 msecs (HTTP/1.1 500) 4 headers in 144 bytes (1 switches on core 0)
29/01/2018 11:26:0510.42.201.252 - - [29/Jan/2018:11:26:05 +0000] "POST /api/schedule/ HTTP/1.1" 500 10446 "https://serol-beta.lco.global/challenge/5/observe/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0" "131.251.254.100, 207.71.206.61"
```

**Comment by zemogle** [comment]
I think having this on the `save()` method of the serialiser was a mistake. I've moved the submit to a different part of the code and all seems well.

**Comment by zemogle** [comment]
Finally figured this out (with the help of functional tests). The submit button was being converted in the "accept" button, so after the submit, users would press it again to move on. Javascript would then post the request again.
